# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\",\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"!\n\x0eKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"*\n\tTermsList\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\x95\x02\n\x0fGlossaryService\x12-\n\x07\x41\x64\x64Term\x12\x0e.glossary.Term\x1a\x12.glossary.Response\x12\x33\n\x07GetTerm\x12\x18.glossary.KeywordRequest\x1a\x0e.glossary.Term\x12\x30\n\x08GetTerms\x12\x0f.glossary.Empty\x1a\x13.glossary.TermsList\x12\x30\n\nUpdateTerm\x12\x0e.glossary.Term\x1a\x12.glossary.Response\x12:\n\nDeleteTerm\x12\x18.glossary.KeywordRequest\x1a\x12.glossary.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=28
  _globals['_TERM']._serialized_end=72
  _globals['_KEYWORDREQUEST']._serialized_start=74
  _globals['_KEYWORDREQUEST']._serialized_end=107
  _globals['_EMPTY']._serialized_start=109
  _globals['_EMPTY']._serialized_end=116
  _globals['_TERMSLIST']._serialized_start=118
  _globals['_TERMSLIST']._serialized_end=160
  _globals['_RESPONSE']._serialized_start=162
  _globals['_RESPONSE']._serialized_end=189
  _globals['_GLOSSARYSERVICE']._serialized_start=192
  _globals['_GLOSSARYSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
